#
# Your Crowdin credentials
#
"project_id_env" : "CROWDIN_PROJECT_ID"
"api_token_env" : "CROWDIN_PERSONAL_TOKEN"
"base_path" : "."
"base_url" : "https://api.crowdin.com"

#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": true
#
# Files configuration
#
files: [
  {
    "source" : "/app-center-webapps/src/main/resources/locale/navigation/portal/global_en.properties",
    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "hub/app__center/global.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/app-center-services/src/main/resources/locale/addon/appcenter_en.properties",
    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "hub/app__center/appCenterPortlets.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/app-center-webapps/src/main/resources/locale/portlet/GeneralSettings_en.properties",
    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "hub/app__center/GeneralSettings.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source": "/app-center-webapps/src/main/resources/locale/portlet/MyApplications_en.properties",
    "translation": "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace": { YML_CROWDIN_LANGUAGES_ARG },
    "dest": "hub/app__center/MyApplications.properties",
    "update_option": "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes": 0,
  },
  {
    "source": "/app-center-webapps/src/main/resources/locale/portlet/LayoutEditor_en.properties",
    "translation": "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace": { YML_CROWDIN_LANGUAGES_ARG },
    "dest": "hub/app__center/LayoutEditor.properties",
    "update_option": "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes": 0,
  }
]
